<wsdl:definitions 
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
	xmlns:tns="http://services.bamnetworks.com/media/2.0" 
	xmlns:scma="http://services.bamnetworks.com/media/types/2.0" 
	xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" 
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"  
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	targetNamespace="http://services.bamnetworks.com/media/2.0">
	<wsdl:documentation>MediaService2_0</wsdl:documentation>
	<wsdl:types>
		<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://services.bamnetworks.com/media/2.0">
			<xs:import namespace="http://services.bamnetworks.com/media/types/2.0" schemaLocation="MediaService.xsd"/>
		</xs:schema>
	</wsdl:types>
	<wsdl:message name="findMediaRequestMessage">
		<wsdl:part name="part1" element="scma:user-verified-media-request"/>
	</wsdl:message>
	<wsdl:message name="findMediaResponseMessage">
		<wsdl:part name="part1" element="scma:user-verified-media-response"/>
	</wsdl:message>
	<wsdl:portType name="MediaService2_0PortType">
		<wsdl:operation name="find">
			<wsdl:input xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" message="tns:findMediaRequestMessage" wsaw:Action="find"/>
			<wsdl:output xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" message="tns:findMediaResponseMessage" wsaw:Action="http://services.bamnetworks.com/media/2.0/mediaInterface/findResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="MediaService2_0SOAP11Binding" type="tns:MediaService2_0PortType">
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
		<wsdl:operation name="find">
			<soap:operation soapAction="find" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	
	<wsdl:service name="MediaService2_0">
		<wsdl:port name="MediaService2_0SOAP11port_http" binding="tns:MediaService2_0SOAP11Binding">
			<soap:address location="http://www.mlb.com/pubajaxws/services/MediaService2_0"/>
		</wsdl:port>
		
	</wsdl:service>
</wsdl:definitions>
